/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Color;
import javax.swing.JOptionPane;
import modelo.Pessoa;

/**
 *
 * @author JoaoVitor
 * @since 28/05/2017 - 13:48
 * @version 1.0 Beta
 */
public class UiCalPessoa extends javax.swing.JInternalFrame {

    /**
     * Creates new form UiCalPessoa
     */
    public UiCalPessoa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPlanetas = new javax.swing.ButtonGroup();
        jlDados = new javax.swing.JLayeredPane();
        jlPesoNaTerra = new javax.swing.JLabel();
        jtPeso = new javax.swing.JTextField();
        jbCalcular = new javax.swing.JButton();
        jrMarte = new javax.swing.JRadioButton();
        jrMercurio = new javax.swing.JRadioButton();
        jrNetuno = new javax.swing.JRadioButton();
        jrJupiter = new javax.swing.JRadioButton();
        jrSaturno = new javax.swing.JRadioButton();
        jrPlutao = new javax.swing.JRadioButton();
        jrVenus = new javax.swing.JRadioButton();
        jrUrano = new javax.swing.JRadioButton();

        setClosable(true);
        setIconifiable(true);

        jlDados.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlPesoNaTerra.setText("Peso na Terra(kg)");

        jtPeso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtPesoFocusLost(evt);
            }
        });

        jbCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/calcular.png"))); // NOI18N
        jbCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCalcularActionPerformed(evt);
            }
        });

        bgPlanetas.add(jrMarte);
        jrMarte.setText("Marte");
        jrMarte.setActionCommand("marte");

        bgPlanetas.add(jrMercurio);
        jrMercurio.setText("Mercurio");

        bgPlanetas.add(jrNetuno);
        jrNetuno.setText("Netuno");

        bgPlanetas.add(jrJupiter);
        jrJupiter.setText("Jupiter");

        bgPlanetas.add(jrSaturno);
        jrSaturno.setText("Saturno");

        bgPlanetas.add(jrPlutao);
        jrPlutao.setText("Plutão");

        bgPlanetas.add(jrVenus);
        jrVenus.setText("Venus");

        bgPlanetas.add(jrUrano);
        jrUrano.setText("Urano");

        jlDados.setLayer(jlPesoNaTerra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlDados.setLayer(jtPeso, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlDados.setLayer(jbCalcular, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlDados.setLayer(jrMarte, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlDados.setLayer(jrMercurio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlDados.setLayer(jrNetuno, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlDados.setLayer(jrJupiter, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlDados.setLayer(jrSaturno, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlDados.setLayer(jrPlutao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlDados.setLayer(jrVenus, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlDados.setLayer(jrUrano, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlDadosLayout = new javax.swing.GroupLayout(jlDados);
        jlDados.setLayout(jlDadosLayout);
        jlDadosLayout.setHorizontalGroup(
            jlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlDadosLayout.createSequentialGroup()
                .addGroup(jlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlDadosLayout.createSequentialGroup()
                        .addComponent(jrMarte)
                        .addGap(18, 18, 18)
                        .addComponent(jrJupiter))
                    .addGroup(jlDadosLayout.createSequentialGroup()
                        .addGroup(jlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrNetuno)
                            .addComponent(jrMercurio))
                        .addGap(4, 4, 4)
                        .addGroup(jlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrSaturno)
                            .addComponent(jrPlutao))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrUrano)
                    .addComponent(jrVenus))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jlDadosLayout.createSequentialGroup()
                .addGroup(jlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlDadosLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlPesoNaTerra)
                            .addComponent(jtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jlDadosLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jbCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jlDadosLayout.setVerticalGroup(
            jlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlDadosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlPesoNaTerra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlDadosLayout.createSequentialGroup()
                        .addGroup(jlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrMarte)
                            .addComponent(jrJupiter))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrMercurio)
                            .addComponent(jrSaturno)))
                    .addGroup(jlDadosLayout.createSequentialGroup()
                        .addComponent(jrVenus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrUrano)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrNetuno)
                    .addComponent(jrPlutao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlDados)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlDados, javax.swing.GroupLayout.PREFERRED_SIZE, 191, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalcularActionPerformed
        calcular();
    }//GEN-LAST:event_jbCalcularActionPerformed

    private void jtPesoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtPesoFocusLost
        //este comando deixa vermelho quando der erro
        if(jtPeso.getText().isEmpty()){
            jtPeso.setBackground(Color.decode("#f98000"));
        }else{
            jtPeso.setBackground(Color.white);
           //este comandop deixa verde quando acertar
            jtPeso.setForeground(Color.green);
            
        }//fecha else
    }//GEN-LAST:event_jtPesoFocusLost

    public void  calcular(){
        try {
            Pessoa p = new Pessoa();
            //if novo
            if(jtPeso.getText().isEmpty()){
                throw new NumberFormatException("peso em branco, digite novamente!");
            }else{
                p.setPeso(Integer.parseInt(jtPeso.getText()));
            }
            JOptionPane.showMessageDialog(rootPane, 
                                            "calculo bem sucedido!\n"
                                                    +p.toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,
                                            "Numero invalido\n"
                                                    +e.getMessage());       
        }
        finally{
            System.out.println("passou aqui!");
        }
    }//fecha calcular
    private void limpar() {
        jtPeso.setText(null);
    }//Fecha limpar

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgPlanetas;
    private javax.swing.JButton jbCalcular;
    private javax.swing.JLayeredPane jlDados;
    private javax.swing.JLabel jlPesoNaTerra;
    private javax.swing.JRadioButton jrJupiter;
    private javax.swing.JRadioButton jrMarte;
    private javax.swing.JRadioButton jrMercurio;
    private javax.swing.JRadioButton jrNetuno;
    private javax.swing.JRadioButton jrPlutao;
    private javax.swing.JRadioButton jrSaturno;
    private javax.swing.JRadioButton jrUrano;
    private javax.swing.JRadioButton jrVenus;
    private javax.swing.JTextField jtPeso;
    // End of variables declaration//GEN-END:variables
}
